# Generated by Django 5.1.6 on 2025-02-21 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weblink',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weblink',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='weblink',
            unique_together={('created_by', 'url')},
        ),
    ]
