# Generated by Django 5.1.6 on 2025-02-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0002_weblink_shared_with_alter_weblink_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblink',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='weblink',
            name='is_deleted',
        ),
    ]
