# Generated by Django 5.1.6 on 2025-02-21 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0003_remove_weblink_deleted_at_remove_weblink_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weblink',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='weblink',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='SharedWebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shared_links', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shared_links', to=settings.AUTH_USER_MODEL)),
                ('web_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_records', to='feedmanager.weblink')),
            ],
        ),
    ]
