# Generated by Django 5.1.6 on 2025-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0004_alter_weblink_unique_together_alter_weblink_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblink',
            name='url',
            field=models.URLField(),
        ),
    ]
