# Generated by Django 5.1.6 on 2025-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0005_alter_weblink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblink',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
