# Generated by Django 5.1.6 on 2025-02-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0006_alter_weblink_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblink',
            name='shared_with',
        ),
    ]
