# Generated by Django 5.1.6 on 2025-02-23 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0007_remove_weblink_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedweblink',
            old_name='shared_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='sharedweblink',
            name='permission',
            field=models.CharField(choices=[('read', '읽기'), ('write', '쓰기')], default='read', max_length=10),
        ),
        migrations.AlterField(
            model_name='sharedweblink',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedweblink',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedweblink',
            name='web_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedmanager.weblink'),
        ),
    ]
