# Generated by Django 5.1.6 on 2025-02-25 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedmanager', '0008_rename_shared_at_sharedweblink_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblink',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='sharedweblink',
            unique_together={('web_link', 'recipient')},
        ),
    ]
